### ISSUE TITLE
Testing code coverge

### ISSUE THREAD

**Issue by Ksoy** [AlvinFok/CloudNative_apc_simulator#14]
need more info
ref: https://github.com/marketplace/actions/jest-annotations-coverage

**Comment by joejoe2** [comment]
recommended to use this
https://about.codecov.io/blog/javascript-code-coverage-using-github-actions-and-codecov/

**Comment by Ksoy** [comment]
@AlvinFok Please follow joejoe2's link to set codecov, since you are the project owner I can't set it

**Comment by Ksoy** [comment]
能加 codecov badge 到 README 中嗎？

**Comment by joejoe2** [comment]
在codecov的設定裡應該會有，加到readme會類似這樣
`[![codecov](https://codecov.io/gh/joejoe2/spring-jwt-template/branch/main/graph/badge.svg?token=24IMFJ0D50)](https://codecov.io/gh/joejoe2/spring-jwt-template)`

**Comment by AlvinFok** [comment]
![Screenshot 2022-05-30 at 9 33 24 PM](https://user-images.githubusercontent.com/38035049/171003187-739fd335-0c0c-4434-94a1-94451af72074.png)

加了現在是unknown是因為設定成是main branch的資料，但main未進行coverage test
