### ISSUE TITLE
Degree of Doneness

### ISSUE THREAD

**Issue by AlvinFok** [AlvinFok/CloudNative_apc_simulator#16]
九分熟 Well Done  (70 celsius)
七分熟 Medium Well  (65 celsius)
五分熟 Medium  (55 celsius)
三分熟 Medium Rare  (50 celsius)
一分熟 Rare (45 celsius)

**Comment by joejoe2** [comment]
@AlvinFok 我看Bonus裡沒有這項阿?

**Comment by AlvinFok** [comment]
![Screenshot 2022-06-01 at 3 17 05 PM](https://user-images.githubusercontent.com/38035049/171349104-1f9010c2-d6b2-42a8-9161-7019a68628f2.png)
